<?php

namespace Database\Seeders;

use App\Models\ProductTag;
use Illuminate\Database\Seeder;

class ProductTagSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data=[
            'Anoraks',
            'Capes',
            'Cloaks',
            'Fur Coats',
            'Jackets',
            'Wind Jackets',
            'Blouses',
            'Caps',
            'Cardigans',
            'Corporate Uniform',
            'Denim',
            'Dress Pant',
            'Flannel Pants',
            'Flannel Shirt',
            'Fleece Jackets',
            'Hooded Sweat Shirt',
            'Jackets',
            'Jeans',
            'Jerseys',
            'Long Pant',
            'Petticoats',
            'Polo Shirts',
            'Pullovers',
            'Pyjamas',
            'Scarfs',
            'Shirt-Blouses',
            'Shirts',
            'Shorts',
            'Singlets',
            'Skirts Dresses',
            'Sports Wear',
            'Suits',
            'Sweat Shirts',
            'Sweater',
            'Tank Tops',
            'Tops',
            'Track-Suits',
            'Trousers',
            'T-Shirts',
            'Underwear',
            'Vests',
            'Work Wear',
            'Work Wear',
            'Brassisres',
            'Briefs',
            'Corselettes',
            'Corsets',
            'Garters',
            'Girdles',
            'Inner Wear',
            'Negligee Dressing Gowns',
            'Night Dresses',
            'Night Gowns',
            'Night Pajamas',
            'Night Shirt',
            'Panties',
            'Panty-Girdles',
            'Pantyhose',
            'Slips',
            'Stockings',
            'Swimwear',
            'Tights',
            'Underpants',
            'Brace',
            'Gloves',
            'Scarves',
            'Veils',
            'Blazers',
            'Bow Ties',
            'Cravats',
            'Over Coats',
            'Suits',
            'Suspenders',
            'Ties',
            'Vests',
            'Waistcoats',
            'Cardigan',
            'Denim Pant',
            'Mittens And Mitts',
            'Mufflers',
            'Pullover',
            'Scarfs',
            'Shawls',
            'Ski Suits',
            'Sock',
            'Sweater',
            'Vest',
            'Wool Blazers',
            'Wool Jackets',
            'Woolen Caps',
            'Basic 5 Pocket Trouser',
            'Blouses',
            'Bottom',
            'Breeches',
            'Cargo Pant',
            'Cargo Shorts',
            'Divided Skirts',
            'Dresses',
            'Dressing Gowns',
            'Ensembles',
            'Fleece Pullover',
            'Frock',
            'Handkerchiefs',
            'Hoodie',
            'Inner Wear',
            'Jerseys',
            'Laggings',
            'Mantillas',
            'Musk',
            'Overall',
            'Palazzo',
            'Petticoats',
            'Polo Shirts',
            'Pyjamas',
            'Shirts',
            'Shorts',
            'Skirts',
            'Sleepwear',
            'Top',
            'Track-Suits',
            'Trousers',
            'Wash Cloth',
            'Fingertip Towel',
            'Hand Towel',
            'Bath Towel',
            'Bath Sheets',
            'Face Towel',
            'Kitchen Towel',
            'Spa Towel',
            'Gym Towel',
            'Beach Towel',
            'Pet Towel',
            'Foot Towel',
            'Paper Towel',
            'Tea Towel',
            'Cotton Bed Sheets',
            'Synthetic Flannel Bed Sheets',
            'Tencel Bed Sheets',
            'Silk Bed Sheets',
            'Bamboo Bed Sheets',
            'Microfiber Bed Sheets',
            'Linen Bed Sheets',
            'Sewing Thread',
            'Button',
            'Rivet',
            'Lining',
            'Interlining',
            'Stopper',
            'Lace',
            'Braid',
            'Elastic',
            'Label',
            'Zipper',
            'Motif',
            'Shoulder Pad',
            'Hook & Loop',
            'Twill Tape',
            'Velcro Tape',
            'Pon Pom',
            'Wadding',
            'Ribbon',
            'Hanger',
            'Hangtag',
            'Tissu Paper',
            'Backboard',
            'Neck Board',
            'Paper Band',
            'Pin/Clip',
            'Tag Pin',
            'Poly Bag',
            'Elastic Bag',
            'Mini Poly Bag',
            'Collar Stand',
            'Gum Tape',
            'Scotch Tape',
            'P.P Band',
            'Inner Carton',
            'Outer Carton',
            'Iron Seal',
            'Trapaulin Paper',
            'Carton Sticker',
            'Safety Sticker',
            'Arrow Sticker',
            'Butterfly',
            'Both Side Tape',
            'Plastic Staple',
            'Barcode',
            'Normal Wash',
            'Pigment Wash',
            'Bleach Wash',
            'Stone Wash',
            'Acid Wash',
            'Enzyme Wash',
            'Sand Blasting',
            'Super White Wash',
            'Caustic Wash',
            'Whitework embroidery',
            'Candlewick embroidery',
            'Cross stitch embroidery',
            'Pulled thread embroidery',
            'Hedebo embroidery',
            'Drawn thread embroidery',
            'Hardanger embroidery',
            'Crewel embroidery',
            'Surface embroidery',
            'Goldwork embroidery',
            'Redwork embroidery',
            'Blackwork embroidery',
            'Bluework embroidery',
            'Sashiko embroider',
            'Boucle',
            'Canvas',
            'Challis',
            'Chambray/Oxford',
            'Chiffon',
            'Clip Jacquard',
            'Corduroy',
            'Crepe/CDC',
            'Denim',
            'Dewspo',
            'Dobby',
            'Double Weave',
            'Eyelet',
            'Flannel',
            'Gauze/Double Gauze',
            'Georgette',
            'Jacquard/Brocade',
            'Melton/Boiled',
            'Memory',
            'Organza',
            'Plaid',
            'Plain',
            'Poplin',
            'Ripstop',
            'Satin',
            'Seersucker',
            'TRS',
            'Taffeta',
            'Tweed',
            'Twill',
            'Voile',
            'Crepe Jersey',
            'Dobby/Jacquard',
            'Double Knit/Interlock',
            'Fleece',
            'French Terry',
            'Jersey',
            'Loop Terry',
            'Neoprene/Scuba',
            'Pique',
            'Pointelle',
            'Polar Fleece',
            'Ponte',
            'Rib',
            'Sherpa',
            'Velour',
            'Waffle',
            'Lace',
            'Mesh/Tulle',
            'Raschel',
            'Tricot',
            'Velvet',
            'Chiffon Lining',
            'Satin Lining',
            'Stretch Lining',
            'Taffeta Lining',
            'Interlining',
            'PVC',
            'Sequin',
            'Tyvek',
            'Vegan Fur',
            'Vegan Leather',
            'Vegan Suede',
            'Artificial Fur',
            'Artificial Leather',
            'Fur',
            'Leather',
            'Wool',
            'Merino Wool',
            'Mohair',
            'Alpaca',
            'Cashmere',
            'Angora',
            'Soya or Milk Protein',
            'Matt Cotton',
            'Mercerized Cotton',
            'Bamboo',
            'Silk',
            'Linen',
            'Hemp',
            'Ramie',
            'Microfibre',
            'Metallics',
            'Acrylic',
            'Nylon',
            'Wool and Cotton Mixes',
            'Natural and Synthetic Mixes',
            'Synthetic-Only Mixes',
            'Chenille',
            'Plied Yarn',
            'Eyelash Yarn',
            'Slubby Yarn',
            'Braided Yarn',
            'Loose-Spun Yarn',
            'Tape Yarn',
            'Ribbon Yarn',
            'Bouclé Yarn',
            'Tweed Yarn',
            'Plastic Bags',
            'Wire',
            'Fabric',
            'String',
            'Rubber Yarn',
    ];

        foreach(array_unique($data) as $item){
            ProductTag::create(['name' => strtolower($item)]);
        }

    }
}
